# Generated by Django 4.2.5 on 2023-11-07 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='product',
            field=models.CharField(default='coding', max_length=155),
        ),
    ]
